[package]
name = "revy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
flate2 = "1.0.30"
hex = "0.4.3"
sha1 = "0.10.6"
